### PR TITLE
Linkintegrity for Plone 5

### PR DESCRIPTION
**Pull request by pbauer**
This is the main implementation for Linkintegrity in Plone 5 (PLIP 698 https://github.com/plone/Products.CMFPlone/issues/698) and fixes https://github.com/plone/Products.CMFPlone/issues/255

To work correctly it also depends on the following changes:

- Products.CMFPlone (https://github.com/plone/Products.CMFPlone/pull/834)
- plone.app.content (https://github.com/plone/plone.app.content/pull/51)
- plone.app.contenttypes (https://github.com/plone/plone.app.contenttypes/pull/259)
- plone.app.intid (https://github.com/plone/plone.app.intid/pull/3)
- plone.app.referenceablebehavior (https://github.com/plone/plone.app.referenceablebehavior/pull/6)
- plone.app.upgrade (https://github.com/plone/plone.app.upgrade/pull/43)

Changes that are already merged:

- mockup (https://github.com/plone/mockup/pull/563)

### CODE REVIEW

**Comment by vangheem** [comment]
Is this tested and are we ready to merge everything?

**Comment by pbauer** [comment]
There is the robot-test "Show warning when deleting linked item from foldercontents" (``Products/CMFPlone/tests/robot/test_linkintegrity.robot``) that fails randomly (a timing-issue). I will look at it later today.

**Comment by pbauer** [comment]
@vangheem all test are green now: http://jenkins.plone.org/job/plip-698-linkintegrity/34/

**Comment by vangheem** [comment]
Looks like https://github.com/plone/plone.app.contenttypes/pull/259 has a CI failure. Should I worry about it or do the merge?

**Comment by pbauer** [comment]
That is expected to fail since pa.c.'s travis job tests against PLone 5.0b3 and not the plip-config.

**Comment by vangheem** [comment]
okay, I'm going to be merging! :)

**Comment by vangheem** [comment]
done. thanks @pbauer !!

**Comment by pbauer** [comment]
@vangheem thanks for merging! I'm currently adding changenotes where appropriate and will move some the upgrade-step to the to50beta5 profile.

**Pull request merged**
