### PR TITLE
Backport #95 distinct breaches

### PR DESCRIPTION
**Pull request by jaroel**

### CODE REVIEW

**Comment by jaroel** [comment]
That doesn't seem right.

**Comment by jaroel** [comment]
@jenkins-plone-org please run jobs

**Review by tisto — APPROVED** [review]

**Comment by tisto** [comment]
I have no clue how to test this via CI. I checked out the branch on buildout.coredev 5.2 and this is the result:

````
buildout.coredev-5.2 git:(5.2) ✗ bin/test -s plone.app.linkintegrity
Test-module import failures:

Module: plone.app.linkintegrity.tests.test_info

Traceback (most recent call last):
  File "/Users/timo/workspace/plone/buildout.coredev-5.2/src/plone.app.linkintegrity/plone/app/linkintegrity/tests/test_info.py", line 3, in <module>
    from plone.app.linkintegrity.tests.utils import set_text
ModuleNotFoundError: No module named 'plone.app.linkintegrity.tests.utils'


Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Running:

  Ran 1 tests with 0 failures, 1 errors, 0 skipped in 0.000 seconds.
Running plone.app.linkintegrity.testing.plone.app.linkintegrity:DX:Functional tests:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.zope.Startup in 0.166 seconds.
  Set up plone.app.testing.layers.PloneFixture /Users/timo/.buildout/eggs/pyScss-1.3.7-py3.9-macosx-14.0-x86_64.egg/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
in 9.956 seconds.
  Set up plone.app.event.testing.PAEventLayer in 0.138 seconds.
  Set up plone.app.contenttypes.testing.PloneAppContenttypes in 0.226 seconds.
  Set up plone.app.linkintegrity.testing.LinkIntegrityLayer in 0.000 seconds.
  Set up plone.app.linkintegrity.testing.LinkIntegrityDXLayer Could not install product plone.app.linkintegrity
in 0.410 seconds.
  Set up plone.app.linkintegrity.testing.plone.app.linkintegrity:DX:Functional in 0.000 seconds.
  Running:

  Ran 30 tests with 0 failures, 1 errors, 1 skipped in 9.428 seconds.
Tearing down left over layers:
  Tear down plone.app.linkintegrity.testing.plone.app.linkintegrity:DX:Functional in 0.000 seconds.
  Tear down plone.app.linkintegrity.testing.LinkIntegrityDXLayer in 0.000 seconds.
  Tear down plone.app.linkintegrity.testing.LinkIntegrityLayer in 0.000 seconds.
  Tear down plone.app.contenttypes.testing.PloneAppContenttypes in 0.029 seconds.
  Tear down plone.app.event.testing.PAEventLayer in 0.004 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.032 seconds.
  Tear down plone.testing.zope.Startup in 0.003 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.001 seconds.

Test-modules with import problems:
  plone.app.linkintegrity.tests.test_info
Total: 31 tests, 0 failures, 1 errors, 1 skipped in 20.852 seconds.
````

I don't see how this could be related. Therefore I'd suggest merging this PR and check what Jenkins tells us...

**Comment by tisto** [comment]
Crap. Just realize that I could have used the PR jenkins job...anyways. Jenkins job is running now:

https://jenkins.plone.org/job/plone-5.2-python-2.7/1953/

**Comment by tisto** [comment]
Robot tests: https://jenkins.plone.org/job/plone-5.2-python-2.7-robot-chrome/

**Comment by tisto** [comment]
Fixed the failing test in 3.x branch directly. Same error that I saw locally...

**Pull request merged**
